<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFJELLVa\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFJELLVa/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFJELLVa.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFJELLVa\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerFJELLVa\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'FJELLVa',
    'container.build_id' => 'c093a4d1',
    'container.build_time' => 1581350594,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFJELLVa');
